name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      # Checkout 仓库，以便操作文件
      - uses: actions/checkout@v3
      - name: Update Chinese Readme
        uses: docker://wapedkj/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: zh
          README_FILE: README.md # 指定更新中文 README
          SHOW_SHORT_INFO: False
          SHOW_TIMEZONE: False
          SHOW_OS: False
          SHOW_LANGUAGE: False
          SHOW_EDITORS: False
          SHOW_PROJECTS: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
      - name: Update English Readme
        uses: docker://wapedkj/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: en
          README_FILE: README_en.md # 指定更新英文 README
          SHOW_SHORT_INFO: False
          SHOW_TIMEZONE: False
          SHOW_OS: False
          SHOW_LANGUAGE: False
          SHOW_EDITORS: False
          SHOW_PROJECTS: False
          SHOW_LINES_OF_CODE: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: false
          SHOW_DAYS_OF_WEEK: false
